INSERT INTO cards (
--id,
gameid     ,
plum        ,
scarlet     ,
mustard     ,
peacock     ,
green       ,
white       ,          
rope        ,
pipe        ,
knife       ,
wrench      ,
candlestick ,
revolver    ,            
study       ,
hall        ,
lounge      ,
library     ,
billiard    ,
dining      ,
conservatory,
ballroom    ,
kitchen     )
values (
--0,
'0', 
'Professor Plum',
'Miss Scarlet' ,
'Col. Mustard' ,
'Mrs. Peacock' ,
'Mrs. Green'   ,
NULL,
'Professor Plum',
'Miss Scarlet' ,
'Col. Mustard' ,
'Mrs. Peacock' ,
'Mrs. Green'   ,
NULL,
'Professor Plum',
'Miss Scarlet' ,
'Col. Mustard' ,
'Mrs. Peacock' ,
'Mrs. Green'   ,
'Mrs. White'   ,
NULL,
'Mrs. White'   ,
'Mrs. White'   
);